MeuSiteEmMVC/Controllers/LoginController.cs
using MeuSiteEmMVC.Helper;
using MeuSiteEmMVC.Models;
using MeuSiteEmMVC.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace MeuSiteEmMVC.Controllers
{
    public class LoginController : Controller
    {
        
        private readonly ISessao _sessao;
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly IEmail _email;

        public LoginController(IUsuarioRepositorio usuarioRepositorio, ISessao iSessao, IEmail email)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = iSessao;
            _email = email;
        }

        public IActionResult Index()
        {
            //Se o usuário estiver logado, redirecionar para a home

            if(_sessao.BuscarSessaoDoUsuario() != null) return RedirectToAction("Index", "Home");

            return View();
        }

        public IActionResult RedefinirSenha()
        {
            return View();
        }

        public IActionResult Sair()
        {
            

            _sessao.RemoverSessaoUsuario();

            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public IActionResult Entrar(LoginModel loginModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuario = _usuarioRepositorio.BuscarPorLogin(loginModel.Login);


                    if (usuario != null)
                    {
                        if (usuario.SenhaValida(loginModel.Senha))
                        {
                            _sessao.CriarSessaoDoUsuario(usuario);
                            return RedirectToAction("Index", "Home");

                        }
                        TempData["MensagemErro"] = $"A senha do usuário é inválida. Por favor, tente novamente.";

                    }

                    TempData["MensagemErro"] = $"Usuário e/ou senha estão inválido(s). Por favor, tente novamente.";
                }
                return View("Index");
            } 
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos realizar seu login, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult EnviarLinkParaRedefinirSenha(RedefinirSenhaModel redefinirSenhaModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuario = _usuarioRepositorio.BuscarPorEmailELogin(redefinirSenhaModel.Email, redefinirSenhaModel.Login);


                    if (usuario != null)
                    {
                        string novaSenha = usuario.GerarNovaSenha();
                        string mensagem = $"Sua nova senha é: {novaSenha}";

                       bool emailEnviado = _email.Enviar(usuario.Email, "Sistema de Contatos - Nova Senha", mensagem);

                        if (emailEnviado)
                        {
                            _usuarioRepositorio.Atualizar(usuario);
                            TempData["MensagemSucesso"] = $"Enviamos para o seu email cadastrado uma nova senha.";
                        }
                        else
                        {
                           TempData["MensagemErro"] = $"Não conseguimos enviar ao e-mail, por favor, tente novamente";
                        }
                        
                        return RedirectToAction("Index", "Login");
                    }

                    TempData["MensagemErro"] = $"Não conseguimos redefinir a sua senha, por favor, verifique os dados informados.";
                }
                return View("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos redefinir a sua senha, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

MeuSiteEmMVC/Controllers/RedefinirSenhaController.cs
using Microsoft.AspNetCore.Mvc;

namespace MeuSiteEmMVC.Controllers
{
    public class RedefinirSenhaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MeuSiteEmMVC/Views/Login/Index.cshtml
@model LoginModel
@{
	Layout = "_LayoutDeslogado";
	ViewData["Title"] = "Login";
}

@if(TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

 @if(TempData["MensagemErro"] != null)
   {
    <div class="alert alert-danger" role="alert">
         <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
   }

<h1> </h1>

<form aso-controller="Login" asp-action="Entrar" method="post">
  <div class="form-group">
    <label for="login">Login</label>
    <input type="text" class="form-control" asp-for="Login" id="login"  placeholder="Escreva seu login">
    @Html.ValidationMessageFor(x => x.Login)
   </div>

  <div class="form-group mb-3">
    <label for="senha">Senha</label>
    <input type="password" class="form-control" asp-for="Senha" id="senha" placeholder="Escreva sua senha">
    @Html.ValidationMessageFor(x => x.Senha)
   </div>

   <p class="mb-4 text-center">
       Esqueceu sua senha?
       <a asp-controller="RedefinirSenha" asp-action="Index" class="text-primary text-gradient font-neight-bold">Redefinir minha senha</a>
   </p>
 
  <button type="submit" class="btn btn-primary col-12">Entrar</button>


</form>