MeuSiteEmMVC/Controllers/AlterarSenhaController.cs
using MeuSiteEmMVC.Helper;
using MeuSiteEmMVC.Models;
using MeuSiteEmMVC.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace MeuSiteEmMVC.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;
        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                alterarSenhaModel.Id = usuarioLogado.Id;
                if(ModelState.IsValid)
                {
                    _usuarioRepositorio.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return View("Index", alterarSenhaModel);
                }
                return View("Index", alterarSenhaModel);
            } 
            catch(Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos realizar a troca de senha, por favor, tente novamente! Detalhe do erro: {erro.Message}";

                return View("Index", alterarSenhaModel);
            }
        }
    }
}

MeuSiteEmMVC/Views/AlterarSenha/Index.cshtml
@model AlterarSenhaModel
@{
    ViewData["Title"] = "Alterar senha do usuário";
}

@if(TempData["MensagemSucesso"] != null)
    {
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
    }

    @if(TempData["MensagemErro"] != null)
    {
    <div class="alert alert-danger" role="alert">
         <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
    }

<div class=" text-center">
    <h1 class="display-4">Alterar senha do usuário</h1>

</div>
    <form asp-controller="AlterarSenha" asp-action="Alterar" method="post">
      
        <div class="form-group mb-2">
        <label for="senhaAtual">Senha Atual</label>
        <input type="password" asp-for="SenhaAtual" class="form-control" placeholder="Digite a senha atual do usuário">
        @Html.ValidationMessageFor(x => x.SenhaAtual)
      </div>

      <div class="form-group mb-2">
        <label for="novaSenha">Nova Senha</label>
        <input type="password" asp-for="NovaSenha" class="form-control" placeholder="Digite a nova senha do usuário">
        @Html.ValidationMessageFor(x => x.NovaSenha)
      </div>

      <div class="form-group mb-2">
        <label for="confirmarSenha">Confirmar nova senha</label>
        <input type="password" asp-for="ConfirmarNovaSenha" class="form-control" placeholder="Confirme a nova senha do usuário">
        @Html.ValidationMessageFor(x => x.ConfirmarNovaSenha)
      </div>
     
      <button type="submit" class="btn btn-primary ">Alterar</button>
      <a class="btn btn-secondary" asp-controller="Home" asp-action="Index" role="button">Voltar</a>

    </form>